FROM python:3.10.4-slim-buster

WORKDIR .

COPY  /db /db

COPY  python/requirements.txt   python/requirements.txt

RUN pip install -r   python/requirements.txt

COPY python/main.py  python/main.py

COPY python/images  python/images

CMD ["uvicorn", "python.main:app", "--host", "0.0.0.0", "--port", "9000"]

# STEP4-4では以下は変更しない
# CMD ["python", "-V"]